#!/bin/bash

#
# Automatically download all the torrent in the ~/Download folder
#
program_exists ()
{
    type "$1" &> /dev/null ;
}
update_tracker ()
{
    local aria2_conf="$HOME/.aria2/aria2.conf"
    echo "Updating tracker list, please wait..."
    local list=`wget -qO- https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt|awk NF|sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/,/g'`
    if [ -z "`grep "bt-tracker" $aria2_conf`" ]; then
        echo -e "\nbt-tracker=$list" >>$aria2_conf
        echo bt-tracker added!
    else
        sed -i "" "s@bt-tracker.*@bt-tracker=$list@g" "$aria2_conf"
        echo bt-tracker updated!
    fi
}

main()
{
	set -e
    if ! program_exists aria2c; then
        echo "Please install aria2"
        exit 1
    fi

    if ! program_exists wget; then
        echo "Please install wget"
        exit 1
    fi

    # update tracker first before download
    update_tracker

    # start the download
    local download_dir="$HOME/Downloads"
	cd "$download_dir"
    echo "Getting torrent from: $download_dir"
    for file in *.torrent; do
        if [ "$file" == "*.torrent" ]; then
            echo "No torrent file found"
            exit 1
        else
            file=$download_dir/$file
            echo "Trying to download: $file"
            open -a Terminal
            osascript   -e "tell application \"Terminal\"" \
                        -e "tell application \"System Events\" to keystroke \"t\" using {command down}" \
                        -e "set FilePath to quoted form of \"$file\" as text" \
                        -e "do script \"aria2c \" & FilePath in front window" \
                        -e "end tell"
                        > /dev/null
            echo "$file download triggered!"
        fi
    done
    
    # wait for the tasks to be started and delete torrent
    sleep 5
    for file in *.torrent; do
        if [ "$file" != "*.torrent" ]; then
            mv "$download_dir/$file" "$HOME/.Trash"
            echo "$file moved to Trash!"
        fi
    done
    # exit the main
    exit 1
}

main "$@"
